セレクトボックスコンポーネントの作成
sohosai/qr-frontend pull request #35
Opened 2023-03-21 08:54 UTC by ShiganaiClarineter

2023-03-31 01:41 UTC, iori0705 requested changes
お疲れ様です！storybookでの挙動は良さそうでした！
2点の変更リクエストがあるので、適切に修正をお願いします

2023-03-31 01:41 UTC, iori0705 commented on src/components/SelectBox/index.tsx
> +class SelectBox extends React.Component<Props, State> {
このSelectBoxコンポーネントはclassで定義されています。classでの定義は非推奨らしいので、関数型定義（function）に変更してください

2023-03-31 01:41 UTC, iori0705 commented on src/components/SelectBox/index.tsx
> +  handleOptionChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
handleOptionChangeは、SelectBoxコンポーネント内で定義しないようにしてください（コンポーネント外部で定義したい）。
よって、SelectBoxには、handleOptionChangeを引数として渡してあげるようにしてください。

（外部での定義は、fixtures/index.tsx の25行目に存在します）

2023-08-24 14:27 UTC, puripuri2100 commented
#34 で実装しちゃったので閉じます

2023-08-24 14:27 UTC, closed without merging