テキスト入力フォーム（複数行）を作成する
sohosai/qr-frontend pull request #8
Opened 2023-02-08 13:42 UTC by iori0705

TextAreaコンポーネントを実装しました

2023-02-12 05:14 UTC, momeemt reviewed
レビューしました。少し変更が多いですが、対応してもらえるとありがたいです。

2023-02-12 05:14 UTC, momeemt commented on .gitignore
> +indexfortest.tsx
ローカルで実験のために作成したファイルはコミットせず、さらにgitignoreなどにも追記しないでください。
38行目以下を削除してください。

2023-02-12 05:14 UTC, momeemt commented on components/TextArea.tsx
> +  const [fixturesDescription, setFixturesDescription] = useState("")
現状の実装では、TextAreaコンポーネント内でstateが定義されているため、コンポーネント外（例えば、親コンポーネント）から情報を取り出すことができません。

https://qiita.com/stin_dev/items/fc1dfb2458e9564549b7#%E5%88%B6%E5%BE%A1%E3%81%95%E3%82%8C%E3%81%9F%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AB%E3%81%97%E3%81%BE%E3%81%97%E3%82%87%E3%81%86

などを参考に、現在の値と`onChange`イベント発火時に実行される関数を引数に渡すことで実現してみてください。

2023-02-12 05:14 UTC, momeemt commented on src/pages/index.tsx
>    )
コンポーネントの動作を確認するためにファイルを書き換えても良いですが、その結果をGitに反映させてはいけません。
元の状態に戻すか、入力フォームを`TextArea`コンポーネントに置き換えるようにしてください。

2023-02-12 05:14 UTC, momeemt commented on src/pages/index copy.tsx
> +}
実験のために作成したファイルをgitに反映させてはいけません。このファイルは削除しておいてください。

2023-02-17 04:20 UTC, momeemt requested changes
レビューしました！

2023-02-17 04:20 UTC, momeemt commented on components/TextArea.tsx
> +      {`${label}`}
`{ label }`で良いです

2023-02-17 04:20 UTC, momeemt commented on components/TextArea.tsx
> +  placeholder?: string
`label`、`placeholder` は強制で良いと思います

2023-02-17 12:10 UTC, momeemt requested changes
レビューしました！

2023-02-17 12:10 UTC, momeemt commented on src/components/TextArea.tsx
> +      <input
今回作成するフォームは複数行なので、`input`要素ではなく`textarea`要素を使うのが良いと思います。

2023-02-17 12:10 UTC, momeemt commented on src/components/TextArea.tsx
> +    <label style={{ display: "block" }}>
デザインをつけてみてください！ラベルの色、フォームのサイズなどはFigmaを参考にしてください。

2023-02-17 12:10 UTC, momeemt commented on src/pages/index.tsx
> +            placeholder='placeholder'
ここでは「赤色ケース・緑色パッチシール貼り付け済み」にしてください

2023-02-17 12:10 UTC, momeemt commented on src/pages/index.tsx
> +            label="label"
ここでは「説明」にしてください

2023-02-18 05:33 UTC, momeemt requested changes
レビューしました！ #22 で導入しているStorybookをこちらにもマージして入れたので、

```
yarn install # 新しく入れたパッケージのインストール
yarn storybook # Storybookサーバーの立ち上げ
```

でStorybookを立ち上げて確認してみてください。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/TextArea.stories.tsx
> +  title: 'xxx',
Storybookにおいてのコンポーネント名を設定してください。
qr-frontendではコンポーネントは `Components/component-name` という規則で設定しています。
例えば、QRCodeコンポーネントは `Components/QRCode` です。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/TextArea.stories.tsx
> +  label: 'xxx',
Storybookで表示する、TextAreaコンポーネントのラベルを設定してください。
ここでは前回指定した、「説明」が良いと思います。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/TextArea.stories.tsx
> +  placeholder: 'xxx'
Storybookで表示する、TextAreaコンポーネントのplaceholderを設定してください。
ここでは前回指定した、「赤色ケース・緑色パッチシール貼り付け済み」が良いと思います。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/TextArea.stories.tsx
> +      <TextArea {...args} value={text} onChange={onChange} />
ここ前に気づかずすみません。TextAreaには、発火時に値を変更する`onChange`だけでなく、現在のフォーム値である`value`を渡さなければ変数の変更と同時にUIを変更することができません。
コンポーネントの実装の方で、string型の`value`というフィールドを新たに受け取ってTextAreaの値として設定するようにしてみてください。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +const TextArea = ({ label, text, placeholder, onChange }: TextAreaProps) => {
QRCodeコンポーネントを参考に、コンポーネントの説明をコメントで記述してください。ドキュメントを記述する際のコメントの形式は、

```
/**
 * xxx
 */
```

となっているのでそちらも併せて確認してください。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  label: string;
QRCodeコンポーネントを参考に、Propsのフィールド（属性）の説明をコメントで記述してください。ドキュメントを記述する際のコメントの形式は、
```
/**
 * xxx
 */
```
となっているのでそちらも併せて確認してください。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  }
現状ではクリックした時にオレンジ色の枠が出てしまうので、消すようにしてください（多分「css　フォーカス　input 消す」などと調べたら出ると思う）

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  font-family: "Inter", "sans-serif";
font-familyはglobal.cssで追記するようにしたので不要です。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  font-family: "Inter", "sans-serif";
font-familyはglobal.cssで追記するようにしたので不要です。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  font-size: 12px;
実装して気づいたのですが、小さすぎたので16pxにしてください。Figmaもそのうち更新します

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  font-size: 8px;
実装して気づいたのですが、小さすぎたので12pxにしてください。Figmaもそのうち更新します

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  }
TextAreaの文字が綺麗に見えるように、適切にpaddingを取るようにしてください。

<img width="336" alt="スクリーンショット 2023-02-18 14 30 53" src="https://user-images.githubusercontent.com/43488453/219842963-a153718f-141e-4269-8e35-ec1436938e2f.png">


<img width="636" alt="スクリーンショット 2023-02-18 14 30 27" src="https://user-images.githubusercontent.com/43488453/219842952-ec8c0709-276a-4e66-837d-a46eb39bcd4f.png">

Figmaでは文字の開始までに上・左ともに余白がある

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  }
現在はボーダーが書かれているので削除してください。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +  }
ラベルとTextAreaの距離が近すぎるので、適切に距離をあけてください。4px開けるのがちょうど良いと思います。

2023-02-18 05:33 UTC, momeemt commented on src/components/TextArea/index.tsx
> +      style = {{ display: "block" }}
StyledLabelの定義の中でスタイルは完結するようにして下さい

2023-02-18 11:57 UTC, iori0705 commented on src/components/TextArea/index.tsx
> +  font-family: "Inter", "sans-serif";
atters以降はどういう変更になってますか？

2023-02-18 15:37 UTC, iori0705 commented
https://github.com/sohosai/qr-frontend/pull/8/files#diff-f2fff02f81aec49e252552869f802db98b3124af015eabd7aaa28ed04e146231:~:text=styled.textarea.attrs%3CTextAreaProps%3E

2023-02-18 15:39 UTC, iori0705 commented
atters以降が増えたのはなぜですか
https://github.com/sohosai/qr-frontend/blob/de55e0b06f5bc81bd1c9a5440d72c4141a9a33af/src/components/TextArea/index.tsx#L26-L28

2023-02-18 15:40 UTC, iori0705 commented
labelの下に4px空けますか？ textareaの上に4px空けますか？ それとも2pxずつ空けますか？

2023-02-21 00:09 UTC, momeemt commented
@iori0705  返信が遅れてすみません。

> atters以降が増えたのはなぜですか
TextAreaの`onChange`属性にpropsが受け取った`onChange`関数を渡すためです。
styled-componentsでは、`attrs`関数を使うことでスタイルを当てるタグの属性の設定ができます。

> labelの下に4px空けますか？ textareaの上に4px空けますか？ それとも2pxずつ空けますか？
padding, marginは「最低その長さの領域を確保する」という特徴があります。
つまり、AとBが順に縦に並んでいて、Aのpadding-bottomが2px、Bのpadding-topが2pxだったとき、AもBもそれぞれ最低2px空けば良いと思っているので、AとBの間隔は2pxになります。
したがって、labelの下に4px開けるのが良いと思います。ここでtopではなくbottomで空けているのは、各要素はたいてい上から下に並ぶので、下の余白の方が扱いやすいことが多いからです（記憶ではどちらでも良かったと思うんだけど、先述した性質からとにかく混同させるのが一番ダメで、x-bottomに統一しようと思います）。

2023-02-21 00:22 UTC, momeemt commented
大嘘じゃん
paddingは対象の内側の余白、marginは外側の余白（https://saruwakakun.com/html-css/basic/margin-padding を参照すると分かりやすくて良い）なので上の主張は全てmarginに置き換えてください
ごめん

2023-02-21 14:56 UTC, momeemt approved these changes
LGTM！お疲れ様でした！

2023-02-21 14:56 UTC, merged